### ISSUE TITLE
Scylla Pods OOMKilled

### ISSUE THREAD

**Issue by vladiceanu** [scylladb/scylla-operator#1016]
**Describe the bug**
After upgrading Scylla from version `4.0.8` to `4.6.3` and "migrating" (fresh install) Scylla-Operator from `v0.2.4` to GA `v1.7.2`, our Scylla nodes get OOMKilled after ~30 days of uptime. The memory utilization graph (based on node-exporter metrics by Prometheus) shows very slow, but constant growth in memory utilization.

<img width="1351" alt="Screenshot 2022-08-01 at 9 49 59 AM" src="https://user-images.githubusercontent.com/19838344/182363277-1706c26a-95d1-4293-9217-994644e30d4e.png">

_(metrics are only available as of the 13th of June due to retention)_

The requests and limits for Scylla Pods are set to 56Gi and 7 cores. 

**To Reproduce**
1. Install Scylla operator v1.7.2
2. Create a 3nodes cluster using Scylla Operator

**Expected behavior**
There is no constant increase in memory utilization.

**Config Files**
<details>
<summary>scylla.yaml</summary>

```yaml

apiVersion: v1
data:
  scylla.yaml: |-
    api_address: 127.0.0.1
    api_doc_dir: /opt/scylladb/api/api-doc/
    api_port: 10000
    api_ui_dir: /opt/scylladb/swagger-ui/dist/
    auto_snapshot: false
    authenticator: PasswordAuthenticator
    authorizer: CassandraAuthorizer
    batch_size_fail_threshold_in_kb: 50
    batch_size_warn_threshold_in_kb: 5
    cas_contention_timeout_in_ms: 1000
    cluster_name: scylla
    commitlog_directory: /var/lib/scylla/commitlog
    commitlog_segment_size_in_mb: 32
    commitlog_sync: periodic
    commitlog_sync_period_in_ms: 10000
    commitlog_total_space_in_mb: -1
    data_file_directories:
    - /var/lib/scylla/data
    hints_directory: /var/lib/scylla/hints
    view_hints_directory: /var/lib/scylla/view_hints
    endpoint_snitch: GossipingPropertyFileSnitch
    listen_address: localhost
    murmur3_partitioner_ignore_msb_bits: 12
    native_transport_port: 9042
    num_tokens: 256
    partitioner: org.apache.cassandra.dht.Murmur3Partitioner
    read_request_timeout_in_ms: 5000
    rpc_address: 0.0.0.0
    rpc_port: 9160
    seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
    parameters:
    - seeds: 127.0.0.1
    write_request_timeout_in_ms: 2000

```
</details>

<details>
<summary>scylla-cr.yaml</summary>

```yaml

......
    agentRepository: scylladb/scylla-manager-agent
    agentVersion: 2.6.3
    cpuset: true
    network:
      hostNetworking: true
    repository: scylladb/scylla
    sysctls:
    - fs.aio-max-nr=2097152
    - fs.file-max=5370890
    - net.core.somaxconn=50000
    - net.netfilter.nf_conntrack_max=5565536
    version: 4.6.3
     .....
    datacenter:
      name: eu-west-1
      racks:
      - agentResources:
          limits:
            cpu: 50m
            memory: 50M
        members: 1
        name: eu-west-1a
        placement:
          .....
          tolerations:
          .....
        resources:
          limits:
            cpu: 7
            memory: 56Gi
          requests:
            cpu: 7
            memory: 56Gi
        scyllaConfig: scylla-config
        storage:
          ....
     # two more racks, same config
    
```
</details>

**Logs**
[scylla_operator_maps.txt](https://github.com/scylladb/scylla-operator/files/9415550/scylla_operator_maps.txt)
[scylla_operator_smaps.txt](https://github.com/scylladb/scylla-operator/files/9415551/scylla_operator_smaps.txt)
[scylla_operator_pmap.txt](https://github.com/scylladb/scylla-operator/files/9415553/scylla_operator_pmap.txt)

<img width="806" alt="Screenshot 2022-08-24 at 1 13 39 PM" src="https://user-images.githubusercontent.com/19838344/186405113-bb9754a3-5732-46b8-b107-94df0d649128.png">

**Environment:**
 - Platform: EKS
 - Kubernetes version:  1.20
 - Scylla version: 4.6.3
 - Scylla-operator version: v1.7.3

**Additional context**
Issue reported first https://github.com/scylladb/scylladb/issues/11191, please see the comments. Tried to set Scylla args: `--memory-lock` and `--memory xG`, but apparently the memory doesn't go to the Scylla process but to PID1 (scylla-operator).
From what can be seen is a high memory utilization by the scylla-operator process (PID 1) within the Pod. 

Please let me know if there are any other details required.
