### ISSUE TITLE
gke: Port yanishark containers to scylla docker repo or remove them

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-operator#119]
We must stop running 3rd party containers in privileged mode.

At the moment we have:

```
 michal@lh:scylladb/scylla-operator (master)$ rg 'image: yanniszark'
examples/gke/cpu-policy-daemonset.yaml
95:        image: yanniszark/kubectl:1.11.5

examples/gke/raid-daemonset.yaml
23:        image: yanniszark/raid-setup:0.1
```

The former is used to update kubelet config with static cpu manager policy using sed and then kill it with -9... It should be possible to do that differently in EKS you can specify that on node creation. Not sure about Google.

The latter could be replaced with scylla image calling scylla_raid_setup. I'm using sth like

```yaml
---
# Source: provisioner/templates/provisioner-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-storage-admin
  namespace: default
  labels:
    heritage: "Helm"
    release: "local-volume"
    chart: provisioner-2.3.4
---
# Source: provisioner/templates/provisioner.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-provisioner-config
  namespace: default
  labels:
    heritage: "Helm"
    release: "local-volume"
    chart: provisioner-2.3.4
data:
  storageClassMap: |
    local-raid-disks:
       hostDir: /mnt/raid-disks
       mountDir: /mnt/raid-disks
       blockCleanerCommand:
         - "/scripts/shred.sh"
         - "2"
       volumeMode: Filesystem
       fsType: xfs
---
# Source: provisioner/templates/provisioner.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-raid-disks
  labels:
    heritage: "Helm"
    release: "local-volume"
    chart: provisioner-2.3.4
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
# Source: provisioner/templates/provisioner-cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-storage-provisioner-node-clusterrole
  labels:
    heritage: "Helm"
    release: "local-volume"
    chart: provisioner-2.3.4
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
# Source: provisioner/templates/provisioner-cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-storage-provisioner-pv-binding
  labels:
    heritage: "Helm"
    release: "local-volume"
    chart: provisioner-2.3.4
subjects:
- kind: ServiceAccount
  name: local-storage-admin
  namespace: default
roleRef:
  kind: ClusterRole
  name: system:persistent-volume-provisioner
  apiGroup: rbac.authorization.k8s.io
---
# Source: provisioner/templates/provisioner-cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-storage-provisioner-node-binding
  labels:
    heritage: "Helm"
    release: "local-volume"
    chart: provisioner-2.3.4
subjects:
- kind: ServiceAccount
  name: local-storage-admin
  namespace: default
roleRef:
  kind: ClusterRole
  name: local-storage-provisioner-node-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
# Source: provisioner/templates/provisioner.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: local-volume-provisioner
  namespace: default
  labels:
    app: local-volume-provisioner
    heritage: "Helm"
    release: "local-volume"
    chart: provisioner-2.3.4
spec:
  selector:
    matchLabels:
      app: local-volume-provisioner
  template:
    metadata:
      labels:
        app: local-volume-provisioner
    spec:
      serviceAccountName: local-storage-admin
      tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: scylla-clusters
        - effect: NoSchedule
          key: role
          operator: Equal
          value: cassandra-stress
      initContainers:
        - name: scylla-raid-setup
          image: scylladb/scylla:4.0.0
          command: ['scylla_raid_setup', '--disks', '/dev/nvme0n1', '--root', '/mnt/raid-disks/disk0']
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /dev
              name: provisioner-dev
            - mountPath: /mnt/raid-disks
              name: local-raid-disks
              mountPropagation: "Bidirectional"
      containers:
        - image: "quay.io/external_storage/local-volume-provisioner:v2.3.4"
          name: provisioner
          securityContext:
            privileged: true
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JOB_CONTAINER_IMAGE
            value: "quay.io/external_storage/local-volume-provisioner:v2.3.4"
          volumeMounts:
            - mountPath: /etc/provisioner/config
              name: provisioner-config
              readOnly: true
            - mountPath: /dev
              name: provisioner-dev
            - mountPath: /mnt/raid-disks
              name: local-raid-disks
              mountPropagation: "HostToContainer"
      volumes:
        - name: provisioner-config
          configMap:
            name: local-provisioner-config
        - name: provisioner-dev
          hostPath:
            path: /dev
        - name: local-raid-disks
          hostPath:
            path: /mnt/raid-disks
```
