### ISSUE TITLE
cpuset is wrongly set

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-operator#121]
Machine with 8 cores, static cpu scheduler, cpu limit 7

```
        resources:
          limits:
            cpu: 7
            memory: 58G
```

We set both smp and cpuset which is redundant and cpuset is incorrect.

```
ld.so /opt/scylladb/python3/bin/../libexec/python3.7.bin -s /docker-entrypoint.py --listen-address=192.168.72.71 --broadcast-address=10.100.234.97 --broadcast-rpc-address=10.100.234.97 --seeds=10.100.234.97 --developer-mode=0 --smp=7 --cpuset=0-7
```
