### ISSUE TITLE
Support extended nodeDomain in client bundles for AZ awareness

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1226]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Config bundle API should be extended with `nodeDomain` and `nodeDomainType` to support AZ aware drivers.
```yaml
apiVersion: cqlclient.scylla.scylladb.com/v1alpha1
kind: CQLConnectionConfig
parameters:
  defaultConsistency: QUORUM
  defaultSerialConsistency: SERIAL
authInfos:
  admin:
    clientCertificateData: <redacted>
    clientKeyData: <redacted>
    password: cassandra
    username: cassandra
contexts:
  default:
    authInfoName: admin
    datacenterName: <k8s>
currentContext: default
datacenters:
  <k8s>:
    certificateAuthorityData: <redacted>
    nodeDomainType: “Template” # (Template|Domain)
    nodeDomain: “{{ .uuid }}.cql.<sc-ns>.apps.{{ .availabilityZone }}.<k8s>.pub.<domain>”
    server: cql.<sc-ns>.apps.<k8s>.pub.<domain>:9142
```

**What is use case behind this feature:**
Supporting AZ aware driver that can hit a proxy in correct AZ and avoid cross AZ traffic between a proxy and a ScyllaDB node.

**Additional Information:**
