### ISSUE TITLE
examples/generic: prometheus requests to much resources

### ISSUE THREAD

**Issue by enaydanov** [scylladb/scylla-operator#128]
In monitoring section we provide an example of how to start Prometheus and we are requesting 4 CPUs and 16GiB of RAM in our example. I think we can shrink it to consume less resources.

**Comment by dahankzter** [comment]
Can't you use the `--set server.resources.limits.memory=8Gi` or perhaps `-f override.yaml` where you simply specify:
```yaml
server:
    resources:
        limits:
           cpu: 4
           memory: 16Gi
```
