### ISSUE TITLE
ALLOW changing scylla  image registry

### ISSUE THREAD

**Issue by viggin543** [scylladb/scylla-operator#1285]
Currently, Scylla operator does not allow to change the image registry of an existing cluster

** Scylla operator 1.7 ** 

This is unfortunate since it does not allow using a mirrored  image

In my situation, I wanted to replace the following:

```
  scyllaImage:
    tag: 5.2.0
  agentImage:
    tag: 3.0.1
```
from the Cluster CRD 

to:

```
  scyllaImage:
    repository: us.gcr.io/<GCP_PROJECT_ID>/scylladb/scylla
    tag: 5.2.0
  agentImage:
    repository: us.gcr.io/<GCP_PROJECT_ID>/scylladb/scylla-manager-agent
    tag: 3.0.0
```

This would have eliminated the dependency on the docker hub
and also would have provided faster in-region downloads of the image.

But scylla operator does not allow changing thath
