### ISSUE TITLE
Scylla should use qosClass: Guaranteed not Burstable

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-operator#135]
At the moment I can see:

```
  phase: Running
  podIP: 192.168.16.98
  podIPs:
  - ip: 192.168.16.98
  qosClass: Burstable
  startTime: "2020-06-17T09:46:12Z"
```

For a Pod to be given a QoS class of Guaranteed:

* Every Container in the Pod must have a memory limit and a memory request, and they must be the same.
* Every Container in the Pod must have a CPU limit and a CPU request, and they must be the same.

https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/

Some containers / initContainers have `resources: {}` which may break it.
