### ISSUE TITLE
Allow `extraVolumes`, `extraVolumeMounts` & `extraEnvs` in Scylla manager Agent helm charts

### ISSUE THREAD

**Issue by Kavinraja-G** [scylladb/scylla-operator#1395]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
I would like to have `extraVolumes`, `extraVolumeMounts` & `extraEnvs` in the helm chart.

**What is use case behind this feature:**
This will allow the `scylla-manager-agents` to use the IRSA to authenticate with AWS services like S3 for backups. For example in anthos on AWS requires the [mentioned steps](https://cloud.google.com/anthos/clusters/docs/multi-cloud/aws/how-to/use-workload-identity-aws#deploy_a_sample_application) to enable WLI.

**Additional Information:**
Example helm values for scylla manager I'm expecting --
```
    extraEnv:
    - name: AWS_ROLE_ARN
      value: AWS_ROLE_ARN
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/aws-iam-token/serviceaccount/token
    - name: AWS_REGION
      value: AWS_REGION
    extraVolumeMounts:
    - mountPath: /var/run/secrets/aws-iam-token/serviceaccount
      name: aws-iam-token
      readOnly: true
    extraVolumes:
    - name: aws-iam-token
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            audience: sts.amazonaws.com
            expirationSeconds: 86400
            path: token
```

**Comment by Kavinraja-G** [comment]
Please let me know if anything I can help to enable this feature. TY!

**Comment by chidambaram27** [comment]
facing similar issue, scylla manager couldn't able to access buckets while performing backup restore action. Looking for a way to introduce workload identity env variables for scylla manager. 

> {"L":"INFO","T":"2024-08-21T08:33:59.708Z","N":"cluster.client","M":"HTTP retry backoff","operation":"OperationsList","wait":"1s","error":"agent [HTTP 500] error in ListJSON: WebIdentityErr: failed to retrieve credentials\ncaused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity\n\tstatus code: 403, request id: 65f9229d-e343-4457-83d5-398c11fc0a62","_trace_id":"JMhZ4tlTRGGJiCw8-yUlaQ"}

**Comment by rzetelskik** [comment]
@chidambaram27 service account token projection can be set up using a [AWS shared config file](https://docs.aws.amazon.com/sdkref/latest/guide/file-format.html) with volumes and agentVolumeMounts:
- [.spec.datacenter.racks[].volumes[]](https://operator.docs.scylladb.com/stable/api-reference/groups/scylla.scylladb.com/scyllaclusters.html#spec-datacenter-racks-volumes)
- [.spec.datacenter.racks[].agentVolumeMounts[]](https://operator.docs.scylladb.com/stable/api-reference/groups/scylla.scylladb.com/scyllaclusters.html#api-scylla-scylladb-com-scyllaclusters-v1-spec-datacenter-racks-agentvolumemounts)

You'd need to create a secret with the config file
```shell
config=$(cat << EOF
[default]
role_arn=AWS_ROLE_ARN
web_identity_token_file=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
region=AWS_REGION

EOF
)
kubectl -n scylla create secret generic aws-config --from-literal=config=${config}
```

The example ScyllaCluster configuration (limitied to the relevant parts) would be:
```yaml
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla-cluster
spec:
  agentVersion: 3.3.0
  ...
  datacenter:
    name: us-east-1
    racks:
      - name: a
        agentVolumeMounts:
        - mountPath: /var/lib/scylla-manager/.aws/config
          subPath: config
          name: aws-config
          readOnly: true
        - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
          name: aws-iam-token
          readOnly: true
        volumes:
        - name: aws-config
          secret:
            secretName: aws-config
        - name: aws-iam-token
          projected:
            defaultMode: 420
            sources:
            - serviceAccountToken:
                audience: sts.amazonaws.com
                expirationSeconds: 86400
                path: token
        ...
```
