### ISSUE TITLE
NodeConfig can't create filesystem on non-physical device

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1397]
*Steps to reproduce*
1. mkdir /mnt/persistent-volumes
2. dd if=/dev/zero of="/mnt/persistent-volumes.img" bs=1024 count=0 seek=20971520
3. kubectl apply
```
apiVersion: scylla.scylladb.com/v1alpha1
kind: NodeConfig
metadata:
  name: cluster
spec:
  localDiskSetup:
    filesystems:
    - device: /mnt/persistent-volumes.img
      type: xfs
    mounts:
    - device: /mnt/persistent-volumes.img
      mountPoint: /mnt/persistent-volumes
      unsupportedOptions:
      - prjquota
  placement:
    nodeSelector:
      scylla.scylladb.com/node-type: scylla
```

The NodeConfig should create the filesystem on `/mnt/persistent-volumes.img`. If it's not a physical device the block size should be defaulted but it should work.

Using RAID related func inside `syncFilesystems` seems a bit fishy as those should be independent sync loops
https://github.com/scylladb/scylla-operator/blob/9518217ba718d30af4343d85959c90b43a47c32a/pkg/controller/nodesetup/sync.go#L44-L68
https://github.com/scylladb/scylla-operator/blob/9518217ba718d30af4343d85959c90b43a47c32a/pkg/controller/nodesetup/sync_filesystems.go#L26-L30

```
I0915 14:24:28.394946       1 nodesetup/sync.go:21] "Finished syncing NodeConfig" NodeConfig="cluster" duration="612.738991ms"
E0915 14:24:28.394998       1 nodesetup/controller.go:192] syncing key 'cluster' failed: failed to sync nodeconfig "cluster": can't sync filesystems: failed to create filesystems: can't determine block size of device "/mnt/persistent-volumes.img" at "/mnt/persistent-volumes.img": can't read device 0:0 logical block size file: open /sys/dev/block/0:0/queue/logical_block_size: no such file or directory
```
