### ISSUE TITLE
Unexpected TLS packet was received errors in db logs

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-operator#1446]
## Issue description

- [X] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Despite all clients using unencrypted ports, in DB logs we can see plenty of errors like:
```
INFO  2023-10-01 02:49:14,270 [shard 13] cql_server - exception while processing connection: std::system_error (error GnuTLS:-15, An unexpected TLS packet was received.)
```

## Impact

unknown, everything otherwise looks ok

## How frequently does it reproduce?

EKS longevity - 2 recent jobs

## Installation details

Kernel Version: 5.10.192-183.736.amzn2.x86_64
Scylla version (or git commit hash): `2023.1.1-20230929.ab1244950a66` with build-id `76e3b93b8680c6c33674b897652b61ff9da1d4d7`

Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.11.0-alpha.0-114-g8ac0a21
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: undefined_region)

Test: `longevity-scylla-operator-3h-eks`
Test id: `85e460ce-52dc-4f36-a93d-0636def0bd0e`
Test name: `scylla-operator/operator-master/eks/longevity-scylla-operator-3h-eks`
Test config file(s):

- [longevity-scylla-operator-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/fa73cde2127567560e3cf64260f55b3275a86a24/test-cases/scylla-operator/longevity-scylla-operator-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 85e460ce-52dc-4f36-a93d-0636def0bd0e`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=85e460ce-52dc-4f36-a93d-0636def0bd0e)
- Show all stored logs command: `$ hydra investigate show-logs 85e460ce-52dc-4f36-a93d-0636def0bd0e`

## Logs:
- **kubernetes-85e460ce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/kubernetes-85e460ce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/kubernetes-85e460ce.tar.gz)
- **db-cluster-85e460ce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/db-cluster-85e460ce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/db-cluster-85e460ce.tar.gz)
- **sct-runner-events-85e460ce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/sct-runner-events-85e460ce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/sct-runner-events-85e460ce.tar.gz)
- **sct-85e460ce.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/sct-85e460ce.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/sct-85e460ce.log.tar.gz)
- **loader-set-85e460ce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/loader-set-85e460ce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/loader-set-85e460ce.tar.gz)
- **monitor-set-85e460ce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/monitor-set-85e460ce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/monitor-set-85e460ce.tar.gz)
- **parallel-timelines-report-85e460ce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/parallel-timelines-report-85e460ce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/parallel-timelines-report-85e460ce.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-eks/124/)
[Argus](https://argus.scylladb.com/test/028aa2df-5ce5-4883-a4a8-16bfbbe8dcc8/runs?additionalRuns[]=85e460ce-52dc-4f36-a93d-0636def0bd0e)
</details>

**Comment by vponomaryov** [comment]
@soyacz 
In the job parameters following was set up:
```
docker_image: scylladb/scylla-nightly
scylla_version: latest
```

Which correctly shown in the pod config:
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/port: "9180"
    prometheus.io/scrape: "true"
    scylla-operator.scylladb.com/force-redeployment-reason: Triggered at 1696129307.3413
  creationTimestamp: "2023-10-01T03:02:44Z"
  generateName: sct-cluster-us-east1-b-us-east1-
  labels:
    app: scylla
    app.kubernetes.io/managed-by: scylla-operator
    app.kubernetes.io/name: scylla
    controller-revision-hash: sct-cluster-us-east1-b-us-east1-7bf887d55d
    scylla/cluster: sct-cluster
    scylla/datacenter: us-east1-b
    scylla/rack: us-east1
    scylla/rack-ordinal: "0"
    scylla/scylla-version: 5.4.0-dev-0.20230930.ecceb554c3a4
    statefulset.kubernetes.io/pod-name: sct-cluster-us-east1-b-us-east1-1
```

But in DB logs we see following:
```
Scylla version 2023.1.1-0.20230929.ab1244950a66 with build-id 76e3b93b8680c6c33674b897652b61ff9da1d4d7 starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-7,9-15 --smp 14 --listen-address 0.0.0.0 --rpc-address 0.0.0.0 --seed-provider-parameters seeds=172.20.21.49 --broadcast-address 172.20.21.49 --broadcast-rpc-address 172.20.21.49 --alternator-address 0.0.0.0 --blocked-reactor-notify-ms 999999999 --enable-sstable-key-validation=1 --prometheus-address=0.0.0.0 --abort-on-lsa-bad-alloc=1 --abort-on-internal-error=1 --abort-on-ebadf=1"
parsed command line options: [log-to-syslog, (positional) 0, log-to-stdout, (positional) 1, default-log-level, (positional) info, network-stack, (positional) posix, io-properties-file: /etc/scylla.d/io_properties.yaml, cpuset, (positional) 1-7,9-15, smp, (positional) 14, listen-address: 0.0.0.0, rpc-address: 0.0.0.0, seed-provider-parameters: seeds=172.20.21.49, broadcast-address: 172.20.21.49, broadcast-rpc-address: 172.20.21.49, alternator-address: 0.0.0.0, blocked-reactor-notify-ms, (positional) 999999999, enable-sstable-key-validation: 1, prometheus-address: 0.0.0.0, abort-on-lsa-bad-alloc: 1, abort-on-internal-error: 1, abort-on-ebadf: 1]
```

So, `5.4.0-latest-dev` image contains enterprise scylla - `2023.1.1-0.20230929.ab1244950a66 with build-id 76e3b93b8680c6c33674b897652b61ff9da1d4d7` ? 
Looks like some mess.
Need to file bug against `scylla`/`scylla packaging`.

@fruch have you seen it before?
