### ISSUE TITLE
The Helm Monitoring stack is not created after setting created and upgrade

### ISSUE THREAD

**Issue by makamekm** [scylladb/scylla-operator#1520]
**Describe the bug**
The Helm Monitoring stack is not created after https://operator.docs.scylladb.com/stable/helm.html#monitoring

**To Reproduce**
1. Create Helm deployment
2. Open and follow https://operator.docs.scylladb.com/stable/helm.html#monitoring
```sh
helm upgrade scylla-operator scylla/scylla-operator --create-namespace --namespace scylla-operator --values ./values.operator.yaml
helm upgrade scylla-manager scylla/scylla-manager --create-namespace --namespace scylla-manager --values ./values.manager.yaml
helm upgrade scylla scylla/scylla --create-namespace --namespace scylla --values ./values.cluster.yaml
```
Alternative command
```sh
helm upgrade --install scylla --namespace scylla scylla/scylla -f ./values.cluster.yaml
```
3. Check that the Monitoring has not been created

**Expected behavior**
Monitoring  has to be created after https://operator.docs.scylladb.com/stable/helm.html#monitoring

**Config Files**

```yaml operator
# Specify desired Scylla Operator image
image:
  tag: latest

# Change log level
logLevel: 2

# Resources allocated to Scylla Operator pods
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 32Mi
```

```yaml cluster
# Version information
scyllaImage:
  tag: 5.2.7
agentImage:
  tag: 3.1.2

# Cluster information
developerMode: true

serviceMonitor:
  create: true

datacenter: manager-dc
racks:
- name: manager-dcb
  members: 2 # better to 2 
  storage:
    capacity: 50Gi
    # storageClassName: xfs-class
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 1
      memory: 1Gi
```

```yaml manager
# Scylla Manager image
image:
  tag: 3.1.2

logLevel: info

# Resources allocated to Scylla Manager pods
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 32Mi

# Resources allocated to Scylla Manager Controller pods
controllerResources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 32Mi

serviceMonitor:
  create: false

# Scylla instance for Manager
scylla:
  cpuset: true
  developerMode: true
  repairs:
    - name: "weekly manager-rack repair"
      intensity: "2"
      interval: "7d"
      dc: [ "manager-dc" ]
  scyllaImage:
    tag: 5.2.7
  agentImage:
    tag: 3.1.2
  datacenter: manager-dc
  racks:
    - name: manager-rack
      members: 2
      storage:
        capacity: 50Gi
        # storageClassName: xfs-class
      resources:
        limits:
          cpu: 1
          memory: 200Mi
        requests:
          cpu: 1
          memory: 200Mi
```

**Logs**
No logs were generated

**Environment:**
 - Platform: Yandex Cloud
 - Kubernetes version: 1.24
 - Scylla versions:
```yaml
scyllaImage:
  tag: 5.2.7
agentImage:
  tag: 3.1.2
# Scylla Manager image
image:
  tag: 3.1.2
```

![image](https://github.com/scylladb/scylla-operator/assets/7905849/be1efd44-cc0c-496d-95f1-dbfd93967722)

**Comment by makamekm** [comment]
> > Monitoring has to be created after https://operator.docs.scylladb.com/stable/helm.html#monitoring
> 
> I don't get this. None of the commands installs (nor is meant to) scyllamonitoring and the docs explicitly say `To spin up a Prometheus monitoring refer to [monitoring guide](https://operator.docs.scylladb.com/stable/monitoring.html).` Have you?

Yes, I tried. But after installing this one. I cannot log in to the Grafana dashboard (using admin:admin).
```yaml scylladbmonitoring
apiVersion: scylla.scylladb.com/v1alpha1
kind: ScyllaDBMonitoring
metadata:
  name: scylla
spec:
  type: Platform
  endpointsSelector:
    matchLabels:
      app.kubernetes.io/name: scylla
      scylla-operator.scylladb.com/scylla-service-type: identity
      scylla/cluster: scylla-manager
  components:
    prometheus:
      storage:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 1Gi
    grafana:
      exposeOptions:
        webInterface:
          ingress:
            ingressClassName: haproxy
            dnsDomains:
            - scylla-grafana.default.svc.cluster.local
            annotations:
              haproxy-ingress.github.io/ssl-passthrough: "true"

```

**Comment by tnozicka** [comment]
> (using admin:admin)

that's because there is are real password - how to get it is described in https://operator.docs.scylladb.com/stable/monitoring.html#prerequisites

**Comment by makamekm** [comment]
Is works wit the command, but there another issue. I have two configs

```yaml manager
apiVersion: scylla.scylladb.com/v1alpha1
kind: ScyllaDBMonitoring
metadata:
  namespace: scylla-manager
  name: scylla
spec:
  type: Platform
  endpointsSelector:
    matchLabels:
      app.kubernetes.io/name: scylla
      # scylla-operator.scylladb.com/scylla-service-type: identity
      # scylla/cluster: scylla
  components:
    prometheus:
      storage:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 1Gi
    grafana:
      exposeOptions:
        webInterface:
          ingress:
            ingressClassName: haproxy
            dnsDomains:
            - scylla-grafana.scylla-manager.svc.cluster.local
            annotations:
              haproxy-ingress.github.io/ssl-passthrough: "true"
```

```yaml cluster
apiVersion: scylla.scylladb.com/v1alpha1
kind: ScyllaDBMonitoring
metadata:
  namespace: scylla
  name: scylla
spec:
  type: Platform
  endpointsSelector:
    matchLabels:
      app.kubernetes.io/name: scylla
      # scylla-operator.scylladb.com/scylla-service-type: identity
      # scylla/cluster: scylla
  components:
    prometheus:
      storage:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 1Gi
    grafana:
      exposeOptions:
        webInterface:
          ingress:
            ingressClassName: haproxy
            dnsDomains:
            - scylla-grafana.scylla.svc.cluster.local
            annotations:
              haproxy-ingress.github.io/ssl-passthrough: "true"
```

So the issue that I see only 1 side:
Manager config:
![image](https://github.com/scylladb/scylla-operator/assets/7905849/2e83beae-2f0b-40c3-be3d-c2acf92f1021)
Cluster config:
![image](https://github.com/scylladb/scylla-operator/assets/7905849/1b8cc220-90b8-4126-96d9-c8ef5862f017)
