### ISSUE TITLE
Operator image introspection fails with EKS and manifests lists

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1647]
When using manifest list the operator image introspection doesn't work on EKS because EKS runtime publishes a reference it can't parse (`:1`).
```yaml
    image: quay.io/scylladb/scylla-operator@sha256:1:1585d371c75584fca5af0be74d9a646be10f4c5775fbc188af7b5eccd330b301
```
```yaml
  containerStatuses:
  - image: quay.io/scylladb/scylla-operator@sha256:1:1585d371c75584fca5af0be74d9a646be10f4c5775fbc188af7b5eccd330b301
    imageID: ""
    lastState: {}
    name: scylla-operator
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: 'Failed to apply default image tag "quay.io/scylladb/scylla-operator@sha256:1:1585d371c75584fca5af0be74d9a646be10f4c5775fbc188af7b5eccd330b301":
          couldn''t parse image reference "quay.io/scylladb/scylla-operator@sha256:1:1585d371c75584fca5af0be74d9a646be10f4c5775fbc188af7b5eccd330b301":
          invalid reference format'
        reason: InvalidImageName
```
```shell
$ containerd --version
containerd github.com/containerd/containerd 1.7.2 0cae528dd6cb557f7201036e9f43420650207b58
```
