### ISSUE TITLE
docs: Issue on page Deploying Scylla on EKS

### ISSUE THREAD

**Issue by gcarmin** [scylladb/scylla-operator#2084]
I would like to report an issue on page https://operator.docs.scylladb.com/v1.13/eks

### Problem

Where this configuration should go?
Which file?

**Comment by tnozicka** [comment]
> Where this configuration should go?

Please be specific about what you mean and what youa sk to be changed

**Comment by gcarmin** [comment]
All of the config snippets that are below this part  - 
https://operator.docs.scylladb.com/v1.13/eks#creating-an-eks-cluster
for example:



    A NodeGroup of 3 i3-2xlarge Nodes, where the Scylla Pods will be deployed. These nodes will only accept pods having scylla-clusters toleration.

```
  - name: scylla-pool
    instanceType: i3.2xlarge
    desiredCapacity: 3
    labels:
      scylla.scylladb.com/node-type: scylla
    taints:
      role: "scylla-clusters:NoSchedule"
    ssh:
      allow: true
    kubeletExtraConfig:
      cpuManagerPolicy: static
```
