### ISSUE TITLE
Manage Pod Disruption Budget

### ISSUE THREAD

**Issue by zimnx** [scylladb/scylla-operator#214]
* Feature Request

Operator should manage PDB to ensure high availability and protect Scylla from voluntary disruptions.  
https://kubernetes.io/docs/concepts/workloads/pods/disruptions/

**Comment by etix** [comment]
I just experienced a Kubernetes upgrade where I ended up with all my Scylla nodes down at the same time (in a 3-nodes cluster). And since Scylla takes some time to start when no seed are available, a simple, supposedly harmless, Kubernetes upgrade can cause a 10min outage. Happily it happened in our staging environment :smile:  

Having support for PDB would at least do a clean rollout, meaning the next node will not be shutdown till the "readiness" of the first one.

I think adding a simple, even not-yet configurable PDB is a  basic requirement for a production use of Scylla in k8s.

The one I'm using will have **at most** one node down:
```yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "scylla.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: scylla
```

This one is the closest to what is happening currently but would ensure that **at least** one node stays up while the others are still rebooting:
```yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "scylla.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: scylla
```
