### ISSUE TITLE
RFC: Add Azure Kubernetes Service (AKS) support

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-operator#2240]
### What should the feature do?

Work on Azure Kubernetes Service (AKS) in the same way it works on GKE, EKS

### What is the use case behind this feature?

Azure users

**Comment by jordanbcooper** [comment]
Can someone perhaps identify what is unsupported about AKS? I could list all of the issues I am having today trying to test this out in my development cluster, but if someone could say, "This is why you shouldn't or **can't** use AKS today" it would save me a lot of spinning wheels. 

Thanks!

**Comment by jordanbcooper** [comment]
@tzach @ylebi

**Comment by mykaul** [comment]
> Can someone perhaps identify what is unsupported about AKS? I could list all of the issues I am having today trying to test this out in my development cluster, but if someone could say, "This is why you shouldn't or **can't** use AKS today" it would save me a lot of spinning wheels.
> 
> Thanks!

It is not tested, so we don't know. It'd be great if you can share your experience thus far.

**Comment by ylebi** [comment]
> Can someone perhaps identify what is unsupported about AKS? I could list all of the issues I am having today trying to test this out in my development cluster, but if someone could say, "This is why you shouldn't or **can't** use AKS today" it would save me a lot of spinning wheels. 
> 
> Thanks!

Hey! As @mykaul mentioned, the ScyllaDB Operator hasn’t been tested on AKS yet, so there might be some issues—things like node configuration, storage, and performance could be tricky. We’re not entirely sure what works and what doesn’t at this point. If you’re able to give it a try and share your experience, that would be super helpful for us. Thanks!

**Comment by jordanbcooper** [comment]
Excellent, thank you! @mykaul and @ylebi!

So, I've been able to deploy scylla-operator and scylla-manager just fine initially, all in its own nodepool on Standard_D4s_v4 VMs.

 I tested its resiliency by just restarting one of the Scylla nodes created, and accidentally when scaling down the nodepool-- causing the pods to shift around. In both cases, there is a multi-attach volume error for one of the pods. After deleting the PVC for the pod, I saw `A node with address...already exists, cancelling join`  in scylla cluster node logs and it never recovers. I have to completely delete both PVs and restart the cluster node pods. 

I cannot think of anything specific to AKS that would cause these issues. Happy to share more configuration, logs, whatever you need. Everything else should be defaults, apart from tolerations/affinities.

I've placed the scylla config from the manager values, and the StorageClass I created below:

```yaml
scylla:
  developerMode: true
  scyllaImage:
    tag: 6.2.0
  agentImage:
    tag: 3.4.0@sha256:441403aed8880cad1feef68aa7a8ee9ffd99a458dc1dcff3dc54ce5bf3cb07b7
  datacenter: manager-dc
  cpuset: false
  automaticOrphanedNodeCleanup: true
  repairs:
    - name: "12h manager-rack repair"
      intensity: "2"
      interval: "12h"
      dc: [ "manager-dc" ]
  racks:
    - name: development
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.azure.com/agentpool
                    operator: In
                    values:
                      - scylla
        tolerations:
          - effect: NoSchedule
            key: pod
            operator: Equal
            value: scylla
      members: 2
      storage:
        capacity: 10Gi
        storageClassName: managed-csi-premium-v2
      resources:
        limits:
          cpu: 1
          memory: 200Mi
        requests:
          cpu: 1
          memory: 200Mi
```

Storage class:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
  name: managed-csi
parameters:
  skuname: StandardSSD_LRS
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
```
