### ISSUE TITLE
ScyllaDBMonitoring: support an external Prometheus instance

### ISSUE THREAD

**Issue by mflendrich** [scylladb/scylla-operator#2490]
Extend ScyllaDBMonitoring to support an external Prometheus instance by:

- Adding a toggle to disable automatic Prometheus object creation.
- Allowing users to specify an external Prometheus endpoint and credentials.
- Configuring the managed Grafana instance to use the external Prometheus as a data source.

Design considerations: https://github.com/scylladb/scylla-operator/issues/2319#issuecomment-2643287819

## Acceptance Criteria
- [ ] Works on OpenShift
- [ ] Works on regular Kubernetes as an alternative to the current way of working (where ScyllaDBMonitoring spins up its own Prometheus)
- [ ] Tested on CI

**Comment by buckleyGI** [comment]
I got it working thanks to the [ScyllaDBMonitoring ](https://operator.docs.scylladb.com/stable/resources/scylladbmonitorings.html)CRD. It's actually an elegant solution.


This CRD is great to get a Prometheus and grafana up and running quickly.
But it isn't made to connect to an existing prometheus that is already running on your k8s cluster which is the majority of uses cases I believe.

But with a small modification to the Prometheus operator, the metrics and alerting+recording rules, are picked up for your existing prometheus.

Just set these keys for the Prometheus CR which makes it pick up any servicemonitors (metrics) and alerting+recording rules

```
ruleSelectorNilUsesHelmValues: false
serviceMonitorSelectorNilUsesHelmValues: false
```

That's it. The only thing that needs happen is to disable the prometheus and grafana made by the ScyllaDBMonitoring CRD.
This is currently not possible so I still have to find a solution for that. To the Scylla team, is it possible to and "enabled: false" keys to these objects?

So only the following objects of the DBMonitoring CRD should be generated in this case (the elegant part is that this is only a subset of what ScyllaDBMonitoring does today, there is nothing new to develop. Thanks to the discoverability and compostability of k8s CRD's)

```
prometheusrule.monitoring.coreos.com/scylla-sed-alerts
prometheusrule.monitoring.coreos.com/scylla-sed-latency
prometheusrule.monitoring.coreos.com/scylla-sed-table

servicemonitor.monitoring.coreos.com/scylla-sed-node-exporter
servicemonitor.monitoring.coreos.com/scylla-sed-scylladb
servicemonitor.monitoring.coreos.com/scylla-sed-service-monitor
```

This leaves the dozen or so grafana dashboards:

```
configmap/scylla-sed-grafana-scylladb-dashboards-manager-3-2
configmap/scylla-sed-grafana-scylladb-dashboards-manager-3-3
configmap/scylla-sed-grafana-scylladb-dashboards-manager-3-4
configmap/scylla-sed-grafana-scylladb-dashboards-scylladb-2022-1
configmap/scylla-sed-grafana-scylladb-dashboards-scylladb-2022-2
configmap/scylla-sed-grafana-scylladb-dashboards-scylladb-2023-1
configmap/scylla-sed-grafana-scylladb-dashboards-scylladb-2024-1
configmap/scylla-sed-grafana-scylladb-dashboards-scylladb-2024-2
configmap/scylla-sed-grafana-scylladb-dashboards-scylladb-5-4
configmap/scylla-sed-grafana-scylladb-dashboards-scylladb-6-0
configmap/scylla-sed-grafana-scylladb-dashboards-scylladb-6-1
configmap/scylla-sed-grafana-scylladb-dashboards-scylladb-6-2
configmap/scylla-sed-grafana-scylladb-dashboards-scylladb-master
```

In our case we manually imported them in our existing Grafana installations.
The same elegant solution doesn't exist as we have with the servicemonitor and prometheusrule CRD's so that is some manually work each time we upgrade scylla and it contains bugfixes are new versions of the dashboard.
If someone can come up with an elegant solution I would be happy to hear that.

**Comment by buckleyGI** [comment]
For reference, I had a small slack discussion with Maciej Zimnoch about this topic

https://scylladb-users.slack.com/archives/C2NLNBXLN/p1741776534732529

**Comment by buckleyGI** [comment]
To disable only the grafana and prometheus pods and let the ScyllaDBMonitoring CRD still create the necessary objects for an existing Prometheus to be picked up (servicemonitor, alertrules,...) we currently have the following solution

```
    apiVersion: scylla.scylladb.com/v1alpha1
    kind: ScyllaDBMonitoring
    metadata:
      name: scylladbmonitoring
    spec:
      components:
        grafana:
          placement:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: nonexistingkey
                    operator: In
                    values:
                    - nonexistingvalue
        prometheus:
          placement:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: nonexistingkey
                    operator: In
                    values:
                    - nonexistingvalue
```

Now the pods are kept in a pending state and don't consume any resources. Is there a better way for the moment?
