### ISSUE TITLE
scylla-manager missing database.hosts

### ISSUE THREAD

**Issue by itboy87** [scylladb/scylla-operator#2536]
### What happened?

After deploying Scylla Manager, its pod fails to start and enters a CrashLoopBackOff state.

<img width="757" alt="Image" src="https://github.com/user-attachments/assets/82837fd6-cb69-4a0f-b186-53a106c66e89" />

Upon checking the logs, I see the following error:
configuration ["/mnt/etc/scylla-manager/scylla-manager.yaml"]: missing database.hosts

STARTUP ERROR: configuration ["/mnt/etc/scylla-manager/scylla-manager.yaml"]: missing database.hosts

### What did you expect to happen?

Scylla Manager should start successfully without errors and run without crashing.

### How can we reproduce it (as minimally and precisely as possible)?

`helm install scylla-manager scylla/scylla-manager --namespace scylla-manager`

After installing Scylla Manager, its pods should be in a running state.

### Scylla Operator version

1.16.0

### Kubernetes platform name and version

```console
Client Version: v1.32.2
Kustomize Version: v5.5.0
Server Version: v1.31.5+k3s1
```

Kubernetes platform info: k3s 1.31.5 installed on three dedicated servers

### Please attach the must-gather archive.

[scylla-operator-must-gather-jbq7z8d84swg.zip](https://github.com/user-attachments/files/19094926/scylla-operator-must-gather-jbq7z8d84swg.zip)

**Comment by zimnx** [comment]
Scylla Manager requires tiny internal Scylla cluster which is used as database, you have deployed it with 0 nodes hence hosts are missing in generated Manager configuration.

Make sure that `scylla-manager` ScyllaCluster in `scylla-manager` namespace has at least 1 node.

**Comment by itboy87** [comment]
Hi @zimnx, I'm not sure I fully understand your point, but here is how I'm installing ScyllaDB using Helm::

1- `helm install scylla-operator scylla/scylla-operator --create-namespace --namespace scylla-operator`

2- `helm install scylla scylla/scylla --create-namespace --namespace scylla -f scylladb-values.yaml`
**scylladb-values.yaml:**
```
developerMode: false
sysctls:
  - "fs.aio-max-nr=30000000"
datacenter: datacenter1
racks:
  - name: datacenter1a
    members: 3
    storage:
      capacity: 100G
      storageClassName: local-path
    resources:
      limits:
        cpu: 8
        memory: 30Gi
      requests:
        cpu: 3
        memory: 1Gi
    placement:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - scylla
              topologyKey: "kubernetes.io/hostname"
```

3- `helm install scylla-manager scylla/scylla-manager --namespace scylla-manager -f scylladb-manager-values.yaml`
**scylladb-manager-values.yaml:**
```
scylla:
  developerMode: false
  racks:
    - name: manager-rack
      storage:
        capacity: 10G
        storageClassName: local-path
      resources:
        limits:
          cpu: 2
          memory: 3Gi
        requests:
          cpu: 1
          memory: 1Gi
```

Please let me know if you need more details or if there’s something specific you’re referring to.

**Comment by zimnx** [comment]
I'm not sure whether Helm merges array items. Since you changed rack resources for scylla-manager ScyllaCluters I assume it used default values for other rack fields. 
I would suggest to fill entire rack spec. You can use [default values.yaml](https://github.com/scylladb/scylla-operator/blob/ac42b958edb46b13ccf8ca2d1fda03b4faa2d6c6/helm/scylla-manager/values.yaml#L67-L93) for reference.

**Comment by itboy87** [comment]
@zimnx thanks it worked after adding all values for rack.
```
scylla:
  developerMode: false
  datacenter: manager-dc
  racks:
    - name: manager-rack
      members: 1
      storage:
        capacity: 10Gi
        storageClassName: local-path
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 1
          memory: 1Gi
      placement:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - scylla
                topologyKey: "kubernetes.io/hostname"
        tolerations:
          - effect: NoSchedule
            key: scylla-operator.scylladb.com/dedicated
            operator: Equal
            value: scyllaclusters
```
