### ISSUE TITLE
docs: Issue on page Helm - the versions and examples are way out of date!

### ISSUE THREAD

**Issue by tluck** [scylladb/scylla-operator#2644]
I would like to report an issue on page https://operator.docs.scylladb.com/v1.17/installation/helm

### Problem

the examples reference OOS vs the newer enterprise 2025.1.2 names etc.

###  Suggest a fix

Update the examples to be in-line and consistent with the latest operator defaults

**Comment by mflendrich** [comment]
@zimnx we discussed in the planning meeting that it was done, but I've just checked and the examples still look old:

[on this page](https://operator.docs.scylladb.com/v1.17/installation/helm) the values are:

```
scyllaImage:
  repository: scylladb/scylla
  tag: 4.3.0

agentImage:
  repository: scylladb/scylla-manager-agent
  tag: 2.2.1
```
