### ISSUE TITLE
Operator creates invalid names for managed resources

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylla-operator#2722]
### What happened?

Creating a v1.ScyllaCluster object with `.metadata.name`, `.spec.datacenter.name` and `.spec.datacenter.racks[].name` such that |`.metadata.name`| + |`.spec.datacenter.name`| and |`.spec.datacenter.racks[].name`| > 63 results in an invalid deployment.

```yaml
  - lastTransitionTime: "2025-06-26T13:08:47Z"
    message: |-
      StatefulSetControllerDegraded: can't create StatefulSet(s): can't create missing statefulset: StatefulSet.apps "simple-pxkn8-remotekubernetescluster-europe-west1-europe-west1-a" is invalid: metadata.name: Invalid value: "simple-pxkn8-remotekubernetescluster-europe-west1-europe-west1-a": must be no more than 63 characters
      ServiceControllerDegraded: Service "simple-pxkn8-remotekubernetescluster-europe-west1-europe-west1-a-0" is invalid: [metadata.name: Invalid value: "simple-pxkn8-remotekubernetescluster-europe-west1-europe-west1-a-0": must be no more than 63 characters, spec.selector: Invalid value: "simple-pxkn8-remotekubernetescluster-europe-west1-europe-west1-a-0": must be no more than 63 characters]
    observedGeneration: 1
    reason: Error,Error
    status: "True"
    type: Degraded
```

### What did you expect to happen?

Operator shouldn't produce invalid names for managed resources. We could generate deterministic names with a hash, similarly to how we do for ScyllaDBManagerClusterRegistrations.

### How can we reproduce it (as minimally and precisely as possible)?

```sh
kubectl apply --server-side -f=- <<EOF
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: simple-pxkn8-remotekubernetescluster
spec:
  agentVersion: 3.5.0
  version: 2025.1.2
  developerMode: true
  automaticOrphanedNodeCleanup: true
  sysctls:
    - fs.aio-max-nr=30000000
  datacenter:
    name: europe-west1
    racks:
      - name: europe-west1-a
        members: 1
        storage:
          capacity: 1Gi
          storageClassName: scylladb-local-xfs
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 1Gi

EOF
```

### Scylla Operator version

master

### Kubernetes platform name and version

<details>
```console
$ kubectl version
Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.30.2
WARNING: version difference between client (1.32) and server (1.30) exceeds the supported minor version skew of +/-1
```

Kubernetes platform info:
</details>

### Please attach the must-gather archive.

n/a
