### ISSUE TITLE
GKE: queue/nomerges is not set

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-operator#280]
**Describe the bug**
Running scylla cluster on GKE results in 

**To Reproduce**
1. Deploy Operator on GKE
2. Deploy scylla nodes
3. Run following command on k8s node:
```
ls -lt /dev/sdb /dev/sdc /dev/sdd | awk '{print("Device: "$10 );printf("Nomerges: ");system("cat /sys/dev/block/"substr($5, 1, length($5)-1)":"$6"/queue/nomerges"); printf("Scheduler: ");system("cat /sys/dev/block/"substr($5, 1, length($5)-1)":"$6"/queue/scheduler");}'
```

result:
```
Device: /dev/sdd
Nomerges: 1
Scheduler: [none] 
Device: /dev/sdc
Nomerges: 1
Scheduler: [none] 
Device: /dev/sdb
Nomerges: 1
Scheduler: [none] 
```

**Expected behavior**
Result should be:
```
Device: /dev/sdd
Nomerges: 2
Scheduler: [none] 
Device: /dev/sdc
Nomerges: 2
Scheduler: [none] 
Device: /dev/sdb
Nomerges: 2
Scheduler: [none] 
```

**Environment:**
 - Platform: GKE
 - Kubernetes version: 1.15.12-gke.20
 - Scylla version: 4.2.0
 - Scylla-operator version: nightly

**Comment by vponomaryov** [comment]
JFYI: in all operator runs we have following message in scylla nodes logs:

```
WARN  2021-05-25 13:56:29,990 [shard 0] iotune - nomerges for /sys/devices/pci0000:00/0000:00:1e.0/nvme/nvme0/nvme0n1/queue/nomerges set to 0. It is recommend to set it to 2 before evaluation so that merges are disabled. Results can be skewed otherwise.
```

So, I think we need fix to this bug to make io assessment provide us adequate results.

**Comment by guitcastro** [comment]
I am getting the same error, using a custom storage class with ssd and xfs

```
  parameters = {
    type                        = "pd-ssd"
    replication-type            = "regional-pd"
    "csi.storage.k8s.io/fstype" = "xfs"
  }
```



```
ERROR:root:['/var/lib/scylla/data'] did not pass validation tests, it may not be on XFS and/or has limited disk space.
This is a non-supported setup, and performance is expected to be very bad.
For better performance, placing your data on XFS-formatted directories is required.
To override this error, enable developer mode as follow:
sudo /opt/scylladb/scripts/scylla_dev_mode_setup --developer-mode 1
tuning /sys/devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:4/0:0:4:0/block/sdc
tuning: /sys/devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:4/0:0:4:0/block/sdc/queue/nomerges 2
warning: unable to tune /sys/devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:4/0:0:4:0/block/sdc/queue/nomerges to 2

failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 27, in <module>
    setup.io()
  File "/scyllasetup.py", line 67, in io
    self._run(['/opt/scylladb/scripts/scylla_io_setup'])
  File "/scyllasetup.py", line 37, in _run
    subprocess.check_call(*args, **kwargs)
  File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
```

any way to troubleshoot why nomerges is not working?

**Comment by dkropachev** [comment]
> I am getting the same error, using a custom storage class with ssd and xfs
> 
> ```
>   parameters = {
>     type                        = "pd-ssd"
>     replication-type            = "regional-pd"
>     "csi.storage.k8s.io/fstype" = "xfs"
>   }
> ```
> 
> ```
> ERROR:root:['/var/lib/scylla/data'] did not pass validation tests, it may not be on XFS and/or has limited disk space.
> This is a non-supported setup, and performance is expected to be very bad.
> For better performance, placing your data on XFS-formatted directories is required.
> To override this error, enable developer mode as follow:
> sudo /opt/scylladb/scripts/scylla_dev_mode_setup --developer-mode 1
> tuning /sys/devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:4/0:0:4:0/block/sdc
> tuning: /sys/devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:4/0:0:4:0/block/sdc/queue/nomerges 2
> warning: unable to tune /sys/devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:4/0:0:4:0/block/sdc/queue/nomerges to 2
> 
> failed!
> Traceback (most recent call last):
>   File "/docker-entrypoint.py", line 27, in <module>
>     setup.io()
>   File "/scyllasetup.py", line 67, in io
>     self._run(['/opt/scylladb/scripts/scylla_io_setup'])
>   File "/scyllasetup.py", line 37, in _run
>     subprocess.check_call(*args, **kwargs)
>   File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 373, in check_call
>     raise CalledProcessError(retcode, cmd)
> ```
> 
> any way to troubleshoot why nomerges is not working?

Could you please provide Scylla version you are running on?
Or even better whole scyllacluster definition

**Comment by guitcastro** [comment]
Sure.

```
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla-cluster
  namespace: scylla
spec:
  agentRepository: docker.io/scylladb/scylla-manager-agent
  agentVersion: 3.1.0
  datacenter:
    name: us-central-1
    racks:
      - agentResources:
          requests:
            cpu: 50m
            memory: 10M
        members: 5
        name: us-central-1
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: failure-domain.beta.kubernetes.io/region
                      operator: In
                      values:
                        - us-central1
                    - key: failure-domain.beta.kubernetes.io/zone
                      operator: In
                      values:
                        - us-central1-a
          tolerations:
            - effect: NoSchedule
              key: role
              operator: Equal
              value: scylla-clusters
        resources:
          limits:
            cpu: '1.5'
            memory: 4Gi
          requests:
            cpu: '1.5'
            memory: 4Gi
        scyllaAgentConfig: scylla-agent-config-secret
        scyllaConfig: scylla-config
        storage:
          capacity: 500G
          storageClassName: regional-ssd-xfs
  repairs:
    - dc:
        - us-central-1
      intensity: '2'
      interval: 7d
      name: weekly us-central-1 repair
      numRetries: 3
      parallel: 0
      smallTableThreshold: 1GiB
      startDate: now
  repository: docker.io/scylladb/scylla
  version: 5.1.9

```
