### ISSUE TITLE
ClusterSpec.SidecarImage does not endup anywhere

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-operator#283]
**Describe the bug**
Deploy cluster with SidecarImage defined or without it does not make any difference

**To Reproduce**
1. Create Operator ...
2. Deploy scylla cluster with SidecarImage defined:
```
spec:
  version: 4.2.0
  agentVersion: 2.2.0
  developerMode: true
  sidecarImage: 
    version: 1.32.0
    repository: busybox
```
3. Run "kubectl get pods -n scylla -o yaml | grep busybox" and you see nothing

**Expected behavior**
To see that sidecar image actually endup in the pod
