### ISSUE TITLE
Scylla wont start due to insufficent memory

### ISSUE THREAD

**Issue by tobad357** [scylladb/scylla-operator#32]
**Describe the bug**
When scylla is coming up it crashes due to insufficient physical memory

Config
```
apiVersion: scylla.scylladb.com/v1alpha1
kind: Cluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: scylla-cluster
spec:
  version: 3.1.0
  developerMode: true
  datacenter:
    name: dc01
    racks:
      - name: rack1
        members: 7
        storage:
          capacity: 1800Gi
        resources:
          requests:
            cpu: 12
            memory: 48Gi
          limits:
            cpu: 12
            memory: 48Gi
```

This results in  env variable inside pod
```
MEMORY=49152
```
And the paramter to docker-entrypoint

```
root         30      6  0 15:35 ?        00:00:00 /opt/scylladb/python3/bin/python3 /opt/scylladb/python3/bin/../libexec/python3.7.bin -s /docker-entrypoint.py --listen-address=10.192.193.12 --broadcast-address=10.192.110.1
67 --broadcast-rpc-address=10.192.110.167 --seeds=10.192.110.167 --developer-mode=1 --smp=12 --memory=48452M```
```

The error when scylla starts up is

```
Could not initialize seastar: std::runtime_error (insufficient physical memory: needed 50805604352 available 47931835136)
```

**Expected behavior**
Scylla to not allocate more memory than what is available

**Config Files**
If relevant, paste your configuration files here (use a pastebin service, such as https://paste.fedoraproject.org/)

**Logs**
```
Could not initialize seastar: std::runtime_error (insufficient physical memory: needed 50805604352 available 47931835136)
```

**Environment:**
 - Platform: Rancker RKE with kuberneets 1.15
 - Kubernetes version: 1.15
 - Scylla version: 3.1.0
 - Scylla-operator version: v0.0-47cba43
