### ISSUE TITLE
How to fix StorageServiceHostIdGet port 10000 check failure

### ISSUE THREAD

**Issue by bzon** [scylladb/scylla-operator#346]
Node Spec is 2 CPU and 7GB RAM

Cluster Yaml:

```yaml
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: simple-cluster
  namespace: scylla-cluster
spec:
  version: 4.2.0
  agentVersion: 2.2.0
  cpuset: true
  sysctls:
    - "fs.aio-max-nr=2097152"
  network:
    hostNetworking: true
  datacenter:
    name: europe-west1
    racks:
      - name: europe-west1-b
        scyllaConfig: "scylla-config"
        scyllaAgentConfig: "scylla-agent-config"
        members: 1
        storage:
          storageClassName: standard
          capacity: 100Gi
        resources:
          requests:
            cpu: 1
            memory: 5Gi
          limits:
            cpu: 1
            memory: 5Gi
        placement:
          tolerations:
          - key: type
            operator: Equal
            value: scylla
            effect: NoSchedule
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: failure-domain.beta.kubernetes.io/zone
                    operator: In
                    values:
                      - europe-west1-b
                - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - scylla
      - name: europe-west1-c
        scyllaConfig: "scylla-config"
        scyllaAgentConfig: "scylla-agent-config"
        members: 1
        storage:
          storageClassName: standard
          capacity: 100Gi
        resources:
          requests:
            cpu: 1
            memory: 5Gi
          limits:
            cpu: 1
            memory: 5Gi
        placement:
          tolerations:
          - key: type
            operator: Equal
            value: scylla
            effect: NoSchedule
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: failure-domain.beta.kubernetes.io/zone
                    operator: In
                    values:
                      - europe-west1-c
                - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - scylla
        volumes:
          - name: coredumpfs
            hostPath:
              path: /tmp/coredumps
        volumeMounts:
          - mountPath: /tmp/coredumps
            name: coredumpfs
      - name: europe-west1-d
        scyllaConfig: "scylla-config"
        scyllaAgentConfig: "scylla-agent-config"
        members: 1
        storage:
          storageClassName: standard
          capacity: 100Gi
        resources:
          requests:
            cpu: 1
            memory: 5Gi
          limits:
            cpu: 1
            memory: 5Gi
        placement:
          tolerations:
          - key: type
            operator: Equal
            value: scylla
            effect: NoSchedule
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: failure-domain.beta.kubernetes.io/zone
                    operator: In
                    values:
                      - europe-west1-d
                - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - scylla
        volumes:
          - name: coredumpfs
            hostPath:
              path: /tmp/coredumps
        volumeMounts:
          - mountPath: /tmp/coredumps
            name: coredumpfs

```

Error:

```
{"L":"INFO","T":"2021-01-26T20:08:35.512Z","N":"member_controller.scylla_client","M":"HTTP retry backoff","operation":"StorageServiceHostIdGet","wait":"34.149993447s","error":"dial tcp 10.8.27.6:10001: connect: connection refused"}
{"L":"DEBUG","T":"2021-01-26T20:08:35.941Z","N":"member_controller.scylla_client","M":"HTTP","host":"10.8.27.6:10001","method":"GET","uri":"/storage_service/host_id","duration":"0ms"}
{"L":"ERROR","T":"2021-01-26T20:08:35.941Z","N":"member_controller","M":"error while executing nodetool status in readiness check","error":"giving up after 10 attempts: dial tcp 10.8.27.6:10001: connect: connection refused","_trace_id":"VeSL9hpURGSJKp-Wy4_6fg","errorStack":"github.com/scylladb/scylla-operator/pkg/scyllaclient.(*retryableOperation).submit\n\t/workspace/pkg/scyllaclient/retry.go:59\ngithub.com/scylladb/scylla-operator/pkg/scyllaclient.retryableTransport.Submit\n\t/workspace/pkg/scyllaclient/retry.go:53\ngithub.com/scylladb/scylla-operator/pkg/scyllaclient/internal/scylla/client/operations.(*Client).StorageServiceHostIDGet\n\t/workspace/pkg/scyllaclient/internal/scylla/client/operations/operations_client.go:10956\ngithub.com/scylladb/scylla-operator/pkg/scyllaclient.(*Client).Status\n\t/workspace/pkg/scyllaclient/client.go:103\ngithub.com/scylladb/scylla-operator/pkg/controllers/sidecar.readinessCheck.func1\n\t/workspace/pkg/controllers/sidecar/checks.go:94\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2416\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2831\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1919\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\n"}
```
