### ISSUE TITLE
Enhance scyllacluster status

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#412]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
ScyllaCluster status should provide more information about the operand state.
This is the current state:
```
    status:
    racks:
      manager-rack:
        members: 1
        readyMembers: 0
        version: 4.2.0
```
missing (not exclusively):
1. Conditions (Available, Progressing, Degraded, ...)
   -  e.g. allows to `kubectl wait --for condition=` so you can programaticaly wait for it to deploy
2. Overall available replicas, ready replicas, replicas, updated replicas
3. Observed generation
