### ISSUE TITLE
Setting up multi-zone cluster does not work

### ISSUE THREAD

**Issue by munjalpatel** [scylladb/scylla-operator#417]
Hello,

I am trying to spread cluster across 3 availability zones in AKS.

When I do this, only 1 node in `zone 1` comes online and the other 2 remains in the `scheduling` state with the following errors:
```
pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 node(s) didn't match node selector, 1 node(s) had volume node affinity conflict
```

Here is the config I am using:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: c001-member
  namespace: my-db
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - "apps"
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - scylla.scylladb.com
    resources:
      - scyllaclusters
    verbs:
      - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: c001-member
  namespace: my-db
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: c001-member
  namespace: my-db
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: c001-member
subjects:
  - kind: ServiceAccount
    name: c001-member
    namespace: my-db
---
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: c001
  namespace: my-db
spec:
  version: 4.2.0
  agentVersion: 2.2.0
  developerMode: true
  automaticOrphanedNodeCleanup: true
  repairs:
  - name: "weekly repair"
    intensity: "2"
    interval: "7d"
  backups:
  - name: "daily full cluster backup"
    location: ["s3:my-preprod-seattle-scylladb-cluster-backup"]
    interval: "1d"
  datacenter:
    name: seattle
    racks:
      - name: z1
        scyllaConfig: "scylla-config"
        scyllaAgentConfig: "scylla-agent-config"
        members: 1
        storage:
          capacity: 15Gi
          storageClassName: default
        resources:
          requests:
            cpu: 150m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 768Mi
        volumes:
          - name: coredumpfs
            hostPath:
              path: /tmp/coredumps
        volumeMounts:
          - mountPath: /tmp/coredumps
            name: coredumpfs
        placement:
          tolerations:
          - effect: NoSchedule
            key: kubernetes.azure.com/scalesetpriority
            operator: Equal
            value: spot
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values: 
                      - westus2
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values: 
                      - westus2-1
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: scylla/cluster
                    operator: In
                    values: ["c001"]
                  - key: scylla/datacenter
                    operator: In
                    values: ["seattle"]
                  - key: scylla/rack
                    operator: In
                    values: ["z1"]
              topologyKey: kubernetes.io/hostname
      - name: z2
        scyllaConfig: "scylla-config"
        scyllaAgentConfig: "scylla-agent-config"
        members: 1
        storage:
          capacity: 15Gi
          storageClassName: default
        resources:
          requests:
            cpu: 150m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 768Mi
        volumes:
          - name: coredumpfs
            hostPath:
              path: /tmp/coredumps
        volumeMounts:
          - mountPath: /tmp/coredumps
            name: coredumpfs
        placement:
          tolerations:
          - effect: NoSchedule
            key: kubernetes.azure.com/scalesetpriority
            operator: Equal
            value: spot
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values: 
                      - westus2
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values: 
                      - westus2-2
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: scylla/cluster
                    operator: In
                    values: ["c001"]
                  - key: scylla/datacenter
                    operator: In
                    values: ["seattle"]
                  - key: scylla/rack
                    operator: In
                    values: ["z2"]
              topologyKey: kubernetes.io/hostname
      - name: z3
        scyllaConfig: "scylla-config"
        scyllaAgentConfig: "scylla-agent-config"
        members: 1
        storage:
          capacity: 15Gi
          storageClassName: default
        resources:
          requests:
            cpu: 150m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 768Mi
        volumes:
          - name: coredumpfs
            hostPath:
              path: /tmp/coredumps
        volumeMounts:
          - mountPath: /tmp/coredumps
            name: coredumpfs
        placement:
          tolerations:
          - effect: NoSchedule
            key: kubernetes.azure.com/scalesetpriority
            operator: Equal
            value: spot
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values: 
                      - westus2
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values: 
                      - westus2-3
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: scylla/cluster
                    operator: In
                    values: ["c001"]
                  - key: scylla/datacenter
                    operator: In
                    values: ["seattle"]
                  - key: scylla/rack
                    operator: In
                    values: ["z3"]
              topologyKey: kubernetes.io/hostname
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: c001-seattle
  namespace: my-db
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      scylla/cluster: c001
      scylla/datacenter: seattle
```
