### ISSUE TITLE
All scylla nodes down during single az control plane upgrade

### ISSUE THREAD

**Issue by etix** [scylladb/scylla-operator#458]
**Describe the bug**
When deploying Scylla on a single AZ (i.e. only a single master) upgrading the Kubernetes master makes all Scylla nodes restart.

**To Reproduce**
1. Deploy a single az Kubernetes cluster (with a version < latest)
2. Deploy Scylla (tested using the helm chart) and wait for the cluster to be up and running.
3. Upgrade the Kubernetes control-plane to the latest version
4. As soon as the control plane is up, you can see the whole Scylla cluster down and restarting

**Expected behavior**
Scylla pods should not restart while the control plane is being upgraded.

**Logs**
I failed to get useful logs of the event since the control plane was down. 

**Environment:**
 - Platform:  GKE
 - Kubernetes version: v1.17.17-gke.1101
 - Scylla version: 4.2.3
 - Scylla-operator version: nightly

**Additional context**
Pods restart without clean shutdown causing log replays on reboot and since all the nodes are down simultaneously the whole cluster is looking for a valid seed and wait for minutes with the message "Connect seeds again" before going back up.

**Comment by tnozicka** [comment]
> Nodes should not restart while the control plane is being upgraded.
Kube update usually means upgrading kubelet on nodes and OS with reboot which drains nodes. For HA setup we are working on adding PDB so only 1 member can be evicted (at a time) when nodes are being drained.

Can you be more specific about your deployment? Was it single node or HA cluster? Schedulable masters?

>I failed to get useful logs of the event since the control plane was down.
Although this doesn't sound like HA setup. Were there other nodes?

**Comment by etix** [comment]
> Kube update usually means upgrading kubelet on nodes and OS with reboot which drains nodes.

The update process on GKE is:
1. Upgrade the master
2. Upgrade the node pools

The issue happened during the master upgrade. All services continued to run except Scylla. I can't tell for sure if Scylla pods went down during the upgrade or right after the master came back up. But I believe it was down the entire process because I reconnected quickly after the master was available again and the pods were restarted uncleanly: the replay log was being replayed and it took a while.

> For HA setup we are working on adding PDB so only 1 member can be evicted (at a time) when nodes are being drained.

I have manually added a PDB to Scylla on this cluster already. The PDB helped during node upgrades, no problem there. The nodes upgrade happened as expected (thanks to the PDB).

> Can you be more specific about your deployment? Was it single node or HA cluster? Schedulable masters?

It's single AZ Kubernetes cluster in `us-central1-c` that is our staging cluster. Our production cluster, which is a regional one (with multiple master) is not affected by this issue. The Scylla cluster has 3 nodes and this is how it is deployed:

```yaml
cpuset: false # if the node has four or fewer CPUs, don’t use this option.
hostNetworking: true
developerMode: false

sysctls:
- "fs.aio-max-nr=2097152"

scyllaImage:
  repository: scylladb/scylla
  # Overrides the image tag whose default is the chart appVersion.
  tag: 4.2.3 # 4.3.0 bug: https://github.com/scylladb/scylla/issues/8032

backups:
- name: "daily backup"
  location: ["gcs:scylla-backups"]
  interval: "1d"
  retention: 31
  keyspace: ["*", "!jaeger_v1"]
repairs:
- name: "repair"
  interval: "2d"
  intensity: "2"
  keyspace: ["*", "!jaeger_v1"]

datacenter: us-central1
racks:
- name: us-central1-c
  members: 3
  storage:
    capacity: 40G
  resources:
    limits:
      cpu: 1
      memory: 5G
    requests:
      cpu: 1
      memory: 5G
  placement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            # for 1.17+ : topology.kubernetes.io/zone
            - key: failure-domain.beta.kubernetes.io/zone
              operator: In
              values:
              - us-central1-c
    tolerations:
      - key: role
        operator: Equal
        value: scylla-clusters
        effect: NoSchedule
  agentVolumeMounts:
    - name: scylla-manager-service-account
      mountPath: /var/run/secret/scylla/
      readOnly: true
  volumes:
    - name: scylla-manager-service-account
      secret:
        secretName: scylla-manager-service-account

# Whether to create Prometheus ServiceMonitor
serviceMonitor:
  create: true
```
