### ISSUE TITLE
"scylla" chart ignores provided storage class

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-operator#485]
**Describe the bug**
File located at "helm/scylla/templates/cluster.yaml" has following line for setting k8s storage class:
```storageClassName: {{ .storage.className }}```

Doc located at "docs/source/scylla_cluster_crd.md" says following:
```
  datacenter:
    name: us-east-1
    racks:
      - name: us-east-1a
        members: 3
        storage:
          capacity: 500G
          storageClassName: local-raid-disks
```

But "helm/scylla/values.schema.json" one has following:
``` 
  "storage": {
      "type": "object",
      "properties": {
          "capacity": {
              "type": "string"
          }
      }
  }
```
And when storage class is provided to the chart it ignores it and default storage class is used.

**To Reproduce**
1. Deploy scylla-operator
2. Create scylla chart providing there non-default storage class
3. See that scylla PVCs get created using default storage class

**Expected behavior**
PVCs use provided non-default storage class

**Config Files**
If relevant, upload your configuration files here using GitHub, there is no need to upload them to any 3rd party services

**Logs**
Please, provide `kubectl get events`, `kubectl logs -n scylla pod-name` and other relevant information.

**Environment:**
 - Platform: GKE
 - Kubernetes version: v1.17.15-gke.800
 - Scylla version: 4.2.0
 - Scylla-operator version: v1.1.0-rc.4-0-g8f2cec5
 - 
**Additional context**
