### ISSUE TITLE
the type storageclass requirement

### ISSUE THREAD

**Issue by yangly0815** [scylladb/scylla-operator#523]
When i deploy a scylla cluster with scylla-oprator, i met a problem:

When i create a storage class，it can't create pvc itself.  Then the pod status is always pending and the description info says,"running "VolumeBinding" filter plugin for pod "simple-cluster-us-east-1-us-east-1a-0": pod has unbound immediate PersistentVolumeClaims" . 

When i create three pvs by meself , the scylla cluster can be created successfully. 

So i want to know why it can't create pvcs by itself? Which type of storageclass does the scylla-operator require?

my storageclass yaml as followings:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: scylla-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
```
