### ISSUE TITLE
Updating scyllaCluster.network.dnsPolicy does not update statefulset

### ISSUE THREAD

**Issue by loopingrage** [scylladb/scylla-operator#526]
**Describe the bug**
Updating `ScyllaCluster.network.dnsPolicy` CR does not trigger an update to the statefulset.

**To Reproduce**
1. Create cluster
```
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla-cluster
  namespace: scylla
spec:
  version: 4.3.2
  agentVersion: 2.2.4
  repository: scylladb/scylla
  developerMode: false
  cpuset: true
  network:
    hostNetworking: false
  datacenter:
    ...
```
2. Update cluster with new dnsPolicy
```
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla-cluster
  namespace: scylla
spec:
  version: 4.3.2
  agentVersion: 2.2.4
  repository: scylladb/scylla
  developerMode: false
  cpuset: true
  network:
    hostNetworking: false
    dnsPolicy: ClusterFirst
  datacenter:
    ...
```
3. Check statefulset

**Expected behavior**
I expected the statefulset template to reflect the new DNS Policy.

**Environment:**
 - Platform: AKS
 - Kubernetes version: 1.19
 - Scylla version: 4.3.2
 - Scylla-operator version: 1.0
