### ISSUE TITLE
Change Cpu Resource In ScyllaCluster Operator Error

### ISSUE THREAD

**Issue by srfaytkn** [scylladb/scylla-operator#536]
When I change resource from ClusterConfig, it throw an error.

**To Reproduce**
1. Create cluster with operator
2. Edit ScyllaCluster file and change cpu resource, save it
3. See error
4. Error: UPGRADE FAILED: cannot patch "scylla" with kind ScyllaCluster: admission webhook "webhook.scylla.scylladb.com" denied the request: rack us-east-2a: changes in resources are not currently supported

**Config Files**
```
before
---
    resources:
      requests:
        cpu: 3
        memory: 4000Mi
      limits:
        cpu: 3
        memory: 4000Mi

after
---
    resources:
      requests:
        cpu: 2
        memory: 4000Mi
      limits:
        cpu: 2
        memory: 4000Mi
```

**Logs**
Error: UPGRADE FAILED: cannot patch "scylla" with kind ScyllaCluster: admission webhook "webhook.scylla.scylladb.com" denied the request: rack us-east-2a: changes in resources are not currently supported

**Environment:**
 - Platform: EKS
 - Kubernetes version: 1.18
 - Scylla version: 4.3.0
 - Scylla-operator version: 1.1
