### ISSUE TITLE
scylla manager chart doesn't allow to provide placement for it's scylla subchart

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-operator#631]
**Describe the bug**
Currently it is not possible to tell scylla manager chart where it's scylla must be scheduled.

If we try to provide following config in values.yaml file:

```
scylla:
  developerMode: true
  scyllaImage:
    tag: 4.3.0
  agentImage:
    tag: 2.2.1
  datacenter: manager-dc
  racks:
  - name: manager-rack
    members: 1
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cloud.google.com/gke-nodepool
              operator: In
              values:
              - scylla-pool
    storage:
      capacity: 5Gi
    resources:
      limits:
        cpu: 1
        memory: 200Mi
      requests:
        cpu: 1
        memory: 200Mi
```

where "placement" field for manager's scylla subchart is specified then we get following error:

```
Error: unable to build kubernetes objects from release manifest: error validating "": 
    error validating data: ValidationError(ScyllaCluster.spec.datacenter.racks[0].placement.nodeAffinity): 
        unknown field "nodeAffinity" in com.scylladb.scylla.v1.ScyllaCluster.spec.datacenter.racks.placement.nodeAffinity
```

Also, it is not possible to update placement of an existing "scyllacluster" CRD which gets created by manager helm chart with following error:

```
Error from server (rack manager-rack: changes in placement are not currently supported): 
    admission webhook "webhook.scylla.scylladb.com" denied the request: 
        rack manager-rack: changes in placement are not currently supported
```

**To Reproduce**
1. Deploy operator
2. Deploy scylla manager using helm chart with "placement" field for scylla subchart.
3. See error

**Expected behavior**
It is expected that all the scylla subchart values are supported by scylla-manager helm chart.

**Config Files**
If relevant, upload your configuration files here using GitHub, there is no need to upload them to any 3rd party services

**Logs**
Please, provide `kubectl get events`, `kubectl logs -n scylla pod-name` and other relevant information.

**Environment:**
 - Platform: GKE
 - Kubernetes version: 1.19.9-gke.1400
 - Scylla version: 4.4.2
 - Scylla-operator version: e.g.: v1.3.0-beta.0-0-gc4dcd8d

**Additional context**
