### ISSUE TITLE
Operator options are not compatible between v1.3 and v1.4-alpha versions causing upgrade failure

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-operator#676]
**Describe the bug**
If we deploy operator v1.3.0 using appropriate Helm chart and then upgrade it using v1.4.0-alpha Helm chart we get following error in the scylla logs for existing scylla cluster:

```
Error: unknown flag: --secret-name
Usage:
   sidecar [flags]

Flags:
      --cpu string             number of cpus to use
  -h, --help                   help for sidecar
      --log-level string       verbosity of the logs. Possible values, in descending order of verbosity: fatal, error, info, debug (default "debug")
      --pod-name string        name of the pod
      --pod-namespace string   namespace of the pod

{"L":"ERROR","T":"2021-07-07T10:50:32.725Z","M":"Root command: a fatal error occured","error":"unknown flag: --secret-name"}
```

Part of scylla pod spec:
```
spec:
  affinity:
    ...
  containers:
  - command:
    - /mnt/shared/scylla-operator
    - sidecar
    - --secret-name=sct-cluster-auth-token
    - --service-name=$(SERVICE_NAME)
    - --cpu-count=$(CPU_COUNT)
    - --loglevel=2
    env:
    - name: SERVICE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: CPU_COUNT
      valueFrom:
        resourceFieldRef:
          containerName: scylla
          divisor: "1"
          resource: limits.cpu
    image: scylladb/scylla:4.4.2
...
    name: scylla
...
```

**To Reproduce**
1. Deploy operator using v1.3.0 Helm chart
2. Deploy a Scylla cluster
3. Upgrade operator using v1.4.0-alpha.0-50-gb19ea00 Helm chart
4. Wait for scylla operator upgrade
5. Wait for scylla cluster upgrade
6. See error

**Expected behavior**
No errors appear, rolling scylla cluster upgrade happens successfully.

**Logs**
Please, provide `kubectl get events`, `kubectl logs -n scylla pod-name` and other relevant information.
[kubernetes-aa06900d.tar.gz](https://github.com/scylladb/scylla-operator/files/6778259/kubernetes-aa06900d.tar.gz)

**Environment:**
 - Platform: EKS
 - Kubernetes version: v1.20.4-eks-6b7464
 - Scylla version: 4.4.2
 - Scylla-operator version: e.g.: v1.4.0-alpha.0-50-gb19ea00

**Additional context**

**Comment by tnozicka** [comment]
hm, why is it trying to run an old image with the new manifest?

>To Reproduce

@vponomaryov if you paste in the exact commands you've used, it's better then a generic description and it helps avoiding misunderstandings ;)

btw. the tar is missing the k8s object dumps

**Comment by vponomaryov** [comment]
> hm, why is it trying to run an old image with the new manifest?
> 
> > To Reproduce
> 
> @vponomaryov if you paste in the exact commands you've used, it's better then a generic description and it helps avoiding misunderstandings ;)
> 
> btw. the tar is missing the k8s object dumps

Uploaded new logs. But, looks liek the problem is in the automation where base image can be picked up having some specific configuration.
Do not spend time on it please while I debug automation for it.

**Comment by vponomaryov** [comment]
@tnozicka I investigated the original problem. It was automation-related. After fixing it and rerunning tests I got another failure.
So, I updated the description with recent data and uploaded recent logs.

**Comment by tnozicka** [comment]
```
{"L":"ERROR","T":"2021-07-07T10:50:32.725Z","M":"Root command: a fatal error occurred","error":"unknown flag: --secret-name"}
```
looks like an old image for the sidecar

**Comment by vponomaryov** [comment]
Here is what I have found in the scylla pod status field:
```
...
  initContainerStatuses:
  - containerID: docker://89d202230c27c26b5bb3cccbde9cf4540fce2e8f077329949ad4fe31ffcf469c
    image: scylladb/scylla-operator:1.3.0
    name: sidecar-injection
...
  - containerID: docker://abcb0bb246571a05351c565233a662322695ded57d931656208735a937d86690
    image: scylladb/scylla-operator:latest
    name: sysctl-buddy
...
```
Looks like "sidecar-injection" init container is not updated like the "sysctl-buddy" one.
