### ISSUE TITLE
Operator and webhook pods shouldn't land on the same node preferably

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#696]
Operator and webhook pods shouldn't land on the same node, if possible. If the node goes down, the service will be lost and not HA. We can't use `requiredDuringSchedulingIgnoredDuringExecution` by default because people might have just one node and the other pod would be forever stuck in pending. But the can readjust the manifest on their own, but we should at least do best effort with `preferredDuringSchedulingIgnoredDuringExecution`.

Something like:
```
podAntiAffinity:
  preferredDuringSchedulingIgnoredDuringExecution:
  - labelSelector:
      matchExpressions:
      - key: app
        operator: In
        values:
        - <app_label>
    topologyKey: "kubernetes.io/hostname"
```
