### ISSUE TITLE
ScyllaCluster pods are not created

### ISSUE THREAD

**Issue by MeydanOzeri** [scylladb/scylla-operator#759]
Im having troubles running the scylla operator on my local kubernetes.
The operator itself gets deployed without issues, but when i deploy a ScyllaCluster its not starting its pods.

The way i configured is as followed:
1. Deployed newest version of CertManager.
2. Deployed the operator from: examples/common/operator.yaml
3. Configured and deployed a ScyllaCluster including its service account and cluster role binding using kustomize.

I would expect the pods to be rolled out, the StatefulSet gets created but it doesn't create any pods.

From examining the operators logs i see this issue:
```
E0814 11:09:09.497857       1 scyllacluster/status.go:86] "Can't get scylla version" err="pod \"development-receiver-scylla-cluster-ds1-ds1-a-0\" not found" ScyllaCluster="development-receiver/development-receiver-scylla-cluster"
```

Im using kubernetes v1.22.
Im deploying through Kustomize.
Im using the latest Scylla version (4.4.4)
Im using the latest Scylla Manager version (2.4.0)
And the latest Scylla Operator version (v1.5.0-alpha.0-46)

I tried changing the versions of everyone of the dependencies but no luck, i still get the same error.

After kustomize builds everything this gets deployed:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: development-receiver
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: development-receiver-scylla-service-account
  namespace: development-receiver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: development-receiver-scylla-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scyllacluster-member
subjects:
- kind: ServiceAccount
  name: development-receiver-scylla-service-account
  namespace: development-receiver
---
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: development-receiver-scylla-cluster
  namespace: development-receiver
spec:
  agentVersion: 2.4.0
  datacenter:
    name: ds1
    racks:
    - members: 3
      name: ds1-a
      resources:
        limits:
          cpu: 2000m
          memory: 2Gi
        requests:
          cpu: 1000m
          memory: 1Gi
      storage:
        capacity: 100Gi
      volumeMounts:
      - mountPath: /tmp/coredumps
        name: coredumpfs
      volumes:
      - hostPath:
          path: /tmp/coredumps
        name: coredumpfs
  developerMode: false
  version: 4.4.4

```

Help would be appreciated.
