### ISSUE TITLE
webhook-server pods are scheduled on the Scylla nodes

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-operator#772]
**Describe the bug**
webhook-server pods are scheduled on the Scylla nodes unexpectedly.

**To Reproduce**
1. Provision K8S cluster of v1.20.4-eks-6b7464
2. Check nodes that webhook-server pods are scheduled on.
Example:
On Scylla node `ip-10-0-0-13.eu-north-1.compute.internal`:
```
- apiVersion: v1
  kind: Node
  metadata:
    labels:
      kubernetes.io/hostname: ip-10-0-0-13.eu-north-1.compute.internal
    name: ip-10-0-0-13.eu-north-1.compute.internal
    resourceVersion: "22621"
```

`webhook-server` is scheduled
```
apiVersion: v1
kind: Pod
metadata:
  generateName: webhook-server-56d5c5cd7-
  labels:
    app.kubernetes.io/instance: webhook-server
    app.kubernetes.io/name: webhook-server
    pod-template-hash: 56d5c5cd7
  name: webhook-server-56d5c5cd7-4h497
  namespace: scylla-operator
  nodeName: ip-10-0-0-13.eu-north-1.compute.internal
```

**Expected behavior**
webhook-server shouldn't be scheduled on the Scylla nodes

**Config Files**
If relevant, upload your configuration files here using GitHub, there is no need to upload them to any 3rd party services

**Logs**
Download logs: https://cloudius-jenkins-test.s3.amazonaws.com/3c8753c0-ebda-438a-a21b-165e2b1948c2/20210816_082032/kubernetes-3c8753c0.tar.gz

**Environment:**
 - Platform: (GKE, Azure, minikube, custom...) EKS
 - Kubernetes version: 1.20.4-eks-6b7464 
 - Scylla version:
 - Scylla-operator version: e.g.: master, 8e155d0...

**Additional context**
