### ISSUE TITLE
Support horizontal autoscaling

### ISSUE THREAD

**Issue by dahankzter** [scylladb/scylla-operator#80]
We should enable and use the "Horizontal Pod Autoscaler" (HPA) to support automatic scale up and downs. We have to make sure there is a latency in the behavior so there can be a smooth and controlled scale up and down. We don't want it to jump up and down...

**Comment by MeydanOzeri** [comment]
any update on that ?

**Comment by mariusz-gomse-centra** [comment]
Hello - is there any update on that? 

I've got one proposition - maybe instead of 1 CRD which is `ScyllaCluster` we can have 2 or 3 CRDs:
* `ScyllaCluster`
* `ScyllaClusterRack`
* maybe also `ScyllaClusterDatacenter`

`ScyllaCluster` will have then definition like:
```
...
spec:
  datacenter:
    name: "simple-datacenter" # it can be also get through labels/selectors 
...
```

`ScyllaClusterDatacenter` will be:
```
metadata:
  name: simple-datacenter
spec:
  racks:
    - name: "us-east-1a"  # it can be also get through labels/selectors 
```

`ScyllaClusterRack` will be:
```
metadata:
  name: "us-east-1a"
spec:
  members: 3
  ...
```

Thx to that we will be able to use [k8s scale subresource](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource) on the `ScyllaClusterRack` and instead of [editing the CR](https://operator.docs.scylladb.com/stable/generic.html#scale-a-scyllacluster) we will be able to do `kubectl scale --replicas=4 scyllaclusterrack/us-east-1a`

Scale subresource can look like this in the
```
subresources:
        scale:
          specReplicasPath: .spec.members
          statusReplicasPath: .status.members
```

Thanks to this for autoscaling later can be use some external tool like [KEDA](https://keda.sh/docs/2.13/concepts/scaling-deployments/#scaling-of-custom-resources)

What do you think about it?
